stages:
- build
- deploy

build:
  stage: build
  script:
  - npm install
  - npm run build:linux
  artifacts:
    paths:
    - dist/*.ico
    - dist/*.AppImage
    expire_in: 1 week
  tags:
  - docker

deploy:
  stage: deploy
  script:
  - cp dist/*.ico /var/www/files/nbb/win64/win64/
  - cp dist/*.AppImage /var/www/files/nbb/linux/
  tags:
  - shell
  only:
  - master
