stages:
- build
- deploy

build:
  stage: build
  script:
  - npm install
  - npm run dist
  artifacts:
    paths:
    - dist/win/*      
    - dist/*.AppImage
    expire_in: 1 week
  tags:
  - docker
