stages:
- build
- deploy

build:
  stage: build
  script:
  - npm install
  - npm run dist
  artifacts:
    paths:
    - dist/win/*      
    - dist/*.AppImage
    expire_in: 1 week
  tags:
  - docker

deploy:
  stage: deploy
  script:
  - cp dist/win/* /var/www/files/nbb/win64/
  - cp dist/*.AppImage /var/www/files/nbb/linux/
  tags:
  - shell
