# vim:ft=ansible:
platform: linux

image_resource:
  type: docker-image
  source: {repository: pikdum/build}

inputs:
  - name: nbb

outputs:
  - name: package

run:
  path: sh
  args: ["nbb/ci/build.sh"]
